required-players: 4

countdown-seconds: 15

lobby-spawn:
  world-name: world
  x: 0
  y: 116
  z: 0
  yaw: 0
  pitch: 0
arenas:
  1:
    world-name: world
    void-level: 20
    spawn:
      world-name: world
      x: -33
      y: 116
      z: 10
      yaw: 0
      pitch: 0
    teams:
      red:
        spawn:
          x: -4
          y: 116
          z: 25
          yaw: 90
          pitch: 0
        bed-location:
          x: -3
          y: 116
          z: 25
          facing: east
      yellow:
        spawn:
          x: -39
          y: 116
          z: 25
          yaw: -90
          pitch: 0
        bed-location:
          x: -40
          y: 116
          z: 25
          facing: west
      green:
        spawn:
          x: -39
          y: 116
          z: 57
          pitch: -90
          yaw: 0
        bed-location:
          x: -39
          y: 116
          z: 57
          facing: west
      blue:
        spawn:
          x: -4
          y: 116
          z: 57
          yaw: 90
          pitch: 0
        bed-location:
          x: -3
          y: 116
          z: 57
          facing: east
